[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/works"
  status = 200
  conditions = { Host = ["blog.velvetmaid.my.id"] }

[[redirects]]
  from = "/"
  to = "/docs"
  status = 200
  conditions = { Host = ["docs.velvetmaid.my.id"] }
