[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/works/:splat"
  status = 200
  force = true
  conditions = { Host = ["blog.velvetmaid.my.id", "www.blog.velvetmaid.my.id"] }