[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://blog.velvetmaid.my.id/"
  to   = "/works/index.html"
  status = 200
  force = true

[[redirects]]
  from = "https://blog.velvetmaid.my.id/*"
  to   = "/works/:splat"
  status = 200
  force = true
